source 'https://rubygems.org/'
    ruby '3.0.0'
    gem 'json'
    gem 'http'
    gem 'watir'
    gem 'rspec'
    gem 'pry'
    gem 'rubocop'
    gem 'dotenv'
    gem 'launchy'
    gem 'sinatra'
    gem 'puma'
    gem 'csv'

gem "shotgun", "~> 0.9.2"
